"""add score to achievement unlocks

Revision ID: a85dd7a17a81
Revises: e51d0e987ba1
Some achievements are found by reading a note rather than counting one, and
those want the similarity that earned them kept: 0.71 is a different claim
from 0.38, and without it a wrong unlock cannot be diagnosed. Nullable,
because a streak has no score and inventing a fake one would be worse than
none.

Create Date: 2026-09-29 00:46:59.330617
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a85dd7a17a81"
down_revision: str | None = "e51d0e987ba1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("achievement_unlocks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("score", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("achievement_unlocks", schema=None) as batch_op:
        batch_op.drop_column("score")

    # ### end Alembic commands ###
